import type { Project, CareerItem, Skill, SiteSettings, ActivityItem, MediaItem } from "./types";

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Portfolio Personnel",
    slug: "portfolio-personnel",
    shortDesc: "Portfolio full-stack avec back-end Express, MySQL et déploiement Docker.",
    description: "Conception et développement d'un portfolio professionnel complet, du design à l'infrastructure. Architecture découplée React / Express avec MySQL et Docker Compose.",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    stack: ["React", "TypeScript", "Express", "MySQL", "Docker"],
    category: "Full-Stack",
    github: "https://github.com",
    demo: "",
    status: "published",
    updatedAt: "2025-06-20",
    context: "Projet personnel visant à présenter mes compétences de manière professionnelle auprès de recruteurs et CTOs.",
    objectives: ["Créer une vitrine professionnelle responsive", "Mettre en place une API REST", "Dockeriser l'environnement"],
    architecture: "Frontend React + TypeScript servi par Vite. Backend Node.js / Express avec MySQL. Docker Compose orchestre les services. GitHub Actions pour le CI.",
    challenges: ["Synchroniser les états React avec l'API distante", "Optimiser le TTI < 1.5s", "Docker multi-service en dev"],
    solutions: ["React Query pour la gestion du cache", "Lazy loading et code splitting", "Docker Compose avec volumes montés"],
    results: "Portfolio en production. Score Lighthouse 95+. Accessible sur mobile et desktop.",
    learnings: ["Architecture front-end scalable avec React + TypeScript", "Gestion de l'état serveur vs local", "CI/CD avec GitHub Actions"],
  },
  {
    id: "2",
    title: "App Rétrospective Agile",
    slug: "retro-agile",
    shortDesc: "Outil collaboratif de rétrospective Scrum avec authentification JWT et vote par équipe.",
    description: "Application permettant aux équipes agiles de réaliser leurs rétrospectives en ligne. Boards collaboratifs, vote, et gestion des actions.",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    stack: ["React", "TypeScript", "Express", "JWT", "MySQL"],
    category: "Full-Stack",
    github: "https://github.com",
    demo: "",
    status: "published",
    updatedAt: "2025-06-15",
    context: "Projet répondant à un besoin réel d'équipes agiles souhaitant digitaliser leurs cérémonies.",
    objectives: ["Authentification sécurisée par JWT", "Board collaboratif avec vote", "Architecture RESTful maintenable"],
    architecture: "SPA React / TypeScript. API REST Express avec middleware JWT. MySQL avec ORM custom. Déployé sur VPS.",
    challenges: ["Sécurisation des routes React", "Relations complexes en MySQL", "UX pour équipes non-tech"],
    solutions: ["Middleware auth + refresh tokens", "Requêtes préparées PDO", "Design system minimaliste"],
    results: "Utilisé par 2 équipes en production. Zéro incident de sécurité signalé.",
    learnings: ["Sécurité applicative (XSS, CSRF, SQL injection)", "Architecture MVC côté API", "UX pour outils internes"],
  },
  {
    id: "3",
    title: "Argent Bank",
    slug: "argent-bank",
    shortDesc: "Application bancaire React avec Redux Toolkit et intégration d'une API REST.",
    description: "Refonte front-end d'une application bancaire simulée. Gestion d'état Redux, authentification et modélisation Swagger.",
    image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    stack: ["React", "Redux", "JavaScript", "Swagger"],
    category: "Frontend",
    github: "https://github.com",
    demo: "",
    status: "published",
    updatedAt: "2025-05-10",
    context: "Projet OpenClassrooms simulant une app bancaire avec authentification et gestion de compte.",
    objectives: ["Implémenter Redux Toolkit", "Intégrer une API REST", "Modéliser les endpoints Swagger"],
    architecture: "React SPA avec Redux Toolkit. Middleware custom pour les appels API. OpenAPI 3.0 pour la documentation.",
    challenges: ["Structurer le store Redux", "Gérer les états de chargement", "Persister la session"],
    solutions: ["Slices Redux Toolkit découplés", "Middleware API centralisé", "LocalStorage avec validation du token"],
    results: "Application fonctionnelle avec couverture complète des user stories OpenClassrooms.",
    learnings: ["Patterns Redux et flux unidirectionnel", "Documentation API OpenAPI", "Architecture front-end data-intensive"],
  },
  {
    id: "4",
    title: "Médiathèque PHP MVC",
    slug: "mediatheque-php",
    shortDesc: "Système de gestion de médiathèque en PHP pur avec pattern MVC from scratch.",
    description: "Application de gestion de livres, films et musiques en PHP natif, sans framework. Pattern MVC implémenté manuellement.",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    stack: ["PHP", "MySQL", "MVC", "HTML/CSS"],
    category: "Backend",
    github: "https://github.com",
    demo: "",
    status: "draft",
    updatedAt: "2025-04-02",
    context: "Projet pédagogique pour comprendre les fondamentaux du back-end sans abstraction.",
    objectives: ["Implémenter MVC sans framework", "CRUD complet", "Sécuriser les requêtes"],
    architecture: "Router PHP custom basé sur les patterns d'URL. MVC strict. PDO pour la base MySQL.",
    challenges: ["Routage PHP natif", "Prévention SQL injection", "Gestion des sessions"],
    solutions: ["Router regex custom", "PDO + requêtes préparées", "Sessions PHP avec régénération d'ID"],
    results: "CRUD fonctionnel pour 3 types de médias. Zéro dépendance externe.",
    learnings: ["Fondamentaux du MVC", "Sécurité PHP / OWASP", "Gestion BDD relationnelle"],
  },
  {
    id: "5",
    title: "Cub3D — École 42",
    slug: "cub3d",
    shortDesc: "Moteur de raycasting 3D en C, inspiré de Wolfenstein. Mathématiques et bas niveau.",
    description: "Implémentation d'un moteur graphique 3D par raycasting en C avec la MiniLibX. Projet emblématique de l'École 42.",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&h=500&fit=crop&auto=format",
    gallery: [],
    stack: ["C", "Raycasting", "Trigonométrie", "MiniLibX"],
    category: "Bas niveau",
    github: "https://github.com",
    demo: "",
    status: "published",
    updatedAt: "2025-03-18",
    context: "Projet phare de l'École 42 démontrant la maîtrise des algorithmes graphiques et des mathématiques.",
    objectives: ["Moteur de raycasting performant", "Gestion des textures", "Parser un fichier de map"],
    architecture: "C natif. Algorithme DDA. MiniLibX pour le rendu. Lookup tables pour sin/cos. Gestion mémoire manuelle.",
    challenges: ["Précision trigonométrique", "Gestion mémoire sans GC", "60 FPS sans optimisations modernes"],
    solutions: ["Lookup tables précalculées", "malloc/free strict (valgrind zero leak)", "Algorithme DDA optimisé"],
    results: "Rendu 3D à 60 FPS. Validation 42 avec note maximale. Zéro memory leak.",
    learnings: ["Mathématiques 3D : trigonométrie, vecteurs, projections", "C bas niveau et gestion mémoire", "Algorithmique de rendu graphique"],
  },
];

export const INITIAL_CAREER: CareerItem[] = [
  {
    id: "1",
    title: "École 42",
    institution: "42 Paris",
    period: "2021",
    description: "Formation intensive par les pairs. Projets bas niveau : gestion mémoire, algorithmes, parseurs, graphique (Cub3D).",
    badge: "Formation",
    order: 1,
    current: false,
  },
  {
    id: "2",
    title: "OpenClassrooms",
    institution: "OpenClassrooms",
    period: "2022",
    description: "Intégrateur Web — HTML/CSS avancé, accessibilité WCAG, responsive design et optimisation des performances.",
    badge: "Diplôme",
    order: 2,
    current: false,
  },
  {
    id: "3",
    title: "La Plateforme",
    institution: "La Plateforme_",
    period: "2023 – 2024",
    description: "Formation full-stack intensive : React, Node.js, PHP, MySQL, Docker. Projets en équipe avec Git flow et code reviews.",
    badge: "Diplôme",
    order: 3,
    current: false,
  },
  {
    id: "4",
    title: "ESGI — Bachelor 3",
    institution: "ESGI Lyon",
    period: "2025",
    description: "Bachelor Ingénierie du Web — architecture web avancée, DevOps, microservices. En alternance.",
    badge: "En cours",
    order: 4,
    current: true,
  },
];

export const INITIAL_SKILLS: Skill[] = [
  { id: "1", name: "React", category: "frontend", order: 1 },
  { id: "2", name: "TypeScript", category: "frontend", order: 2 },
  { id: "3", name: "Next.js", category: "frontend", order: 3 },
  { id: "4", name: "Tailwind CSS", category: "frontend", order: 4 },
  { id: "5", name: "HTML / CSS", category: "frontend", order: 5 },
  { id: "6", name: "Redux", category: "frontend", order: 6 },
  { id: "7", name: "Node.js", category: "backend", order: 1 },
  { id: "8", name: "Express", category: "backend", order: 2 },
  { id: "9", name: "PHP", category: "backend", order: 3 },
  { id: "10", name: "REST API", category: "backend", order: 4 },
  { id: "11", name: "JWT", category: "backend", order: 5 },
  { id: "12", name: "MySQL", category: "database", order: 1 },
  { id: "13", name: "SQL", category: "database", order: 2 },
  { id: "14", name: "PDO", category: "database", order: 3 },
  { id: "15", name: "Docker", category: "devops", order: 1 },
  { id: "16", name: "Git", category: "devops", order: 2 },
  { id: "17", name: "GitHub", category: "devops", order: 3 },
  { id: "18", name: "GitHub Actions", category: "devops", order: 4 },
  { id: "19", name: "Figma", category: "tools", order: 1 },
  { id: "20", name: "Postman", category: "tools", order: 2 },
  { id: "21", name: "VSCode", category: "tools", order: 3 },
  { id: "22", name: "Linux", category: "tools", order: 4 },
];

export const INITIAL_SETTINGS: SiteSettings = {
  heroTitle: "Je développe des applications web modernes.",
  heroSubtitle: "Elyas Benyoub — développeur Front-End & Full-Stack basé à Lyon. Spécialisé React, TypeScript et Next.js.",
  heroAvailable: true,
  email: "elyas.benyoub@email.com",
  github: "https://github.com/elyas-benyoub",
  linkedin: "https://linkedin.com/in/elyas-benyoub",
  location: "Lyon, France",
  cvFilename: "elyas-benyoub-cv-2025.pdf",
  seoTitle: "Elyas Benyoub — Développeur Web Full-Stack React / TypeScript",
  seoDescription: "Portfolio d'Elyas Benyoub, développeur React/TypeScript/Next.js basé à Lyon. En recherche d'alternance Bachelor 3 Ingénierie du Web (ESGI).",
  ogImage: "",
};

export const INITIAL_ACTIVITY: ActivityItem[] = [
  { id: "1", type: "project_updated", label: "Portfolio Personnel — description mise à jour", timestamp: "Il y a 2 heures" },
  { id: "2", type: "project_added", label: "App Rétrospective Agile ajoutée", timestamp: "Il y a 1 jour" },
  { id: "3", type: "skill_added", label: "GitHub Actions ajouté aux compétences", timestamp: "Il y a 2 jours" },
  { id: "4", type: "career_updated", label: "ESGI marqué comme en cours", timestamp: "Il y a 5 jours" },
  { id: "5", type: "settings_updated", label: "Statut disponibilité activé", timestamp: "Il y a 1 semaine" },
];

export const INITIAL_MEDIA: MediaItem[] = [
  { id: "1", url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=300&fit=crop&auto=format", filename: "portfolio-preview.jpg", size: "148 KB", uploadedAt: "20 juin 2025" },
  { id: "2", url: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=300&fit=crop&auto=format", filename: "retro-agile-cover.jpg", size: "204 KB", uploadedAt: "15 juin 2025" },
  { id: "3", url: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=400&h=300&fit=crop&auto=format", filename: "argent-bank-hero.jpg", size: "186 KB", uploadedAt: "10 mai 2025" },
  { id: "4", url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=300&fit=crop&auto=format", filename: "mediatheque-cover.jpg", size: "312 KB", uploadedAt: "2 avril 2025" },
  { id: "5", url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=300&fit=crop&auto=format", filename: "cub3d-render.jpg", size: "255 KB", uploadedAt: "18 mars 2025" },
  { id: "6", url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop&auto=format", filename: "coding-setup.jpg", size: "178 KB", uploadedAt: "5 mars 2025" },
];
